version: '3.8'

services:
  device_client_runtime:
    container_name: device_client_runtime_ad
    build:
      context: ./..
      dockerfile: ./examples/uc4_offload_ad_function.dockerfile
    network_mode: host
    volumes:
    - .:/cognit/examples
    - /etc/response_daemon:/cognit/queue

 